"""
services/audit_service.py
---------------------------
Audit ledger queries and the CSV/PDF export generators. Used by api/audit.py.
"""

import csv
import io
import datetime
from typing import Optional
from sqlalchemy.orm import Session
from sqlalchemy import desc

import models
import services.export_service as export_service
from security import SUPER_ADMIN_EMAIL

# The audit ledger is the one dataset in this app guaranteed to grow
# forever (it's an append-only log -- nothing is ever deleted from it), so
# it gets the smallest DEFAULT_LIMIT of any listing endpoint and the
# frontend (js/components/audit.js) does TRUE server-side paging against
# it -- fetching one page at a time from the API on every "Next"/"rows per
# page" change -- rather than loading the whole table into the browser like
# the other (much smaller, bounded) directories do. See
# js/components/audit.js's module docstring for the full explanation.
DEFAULT_LIMIT = 25
MAX_LIMIT = 200

# SECURITY: "CSV/Formula Injection" (a.k.a. "CSV injection") mitigation.
# Several columns in this export (`operator`, `details`) contain text that
# ultimately originates from things a Super Admin/Manager typed elsewhere
# in the app -- an asset pool's name, an outsider's name/company, a
# maintenance note, etc. (see services/asset_service.py,
# services/user_service.py). See services/export_service.py's
# `csv_safe_cell()` docstring for the full threat model/mitigation -- this
# module reuses that same shared helper (rather than keeping its own copy)
# so every exporter in the app is protected identically.
_csv_safe_cell = export_service.csv_safe_cell


def get_audit_logs(db: Session, user: dict, limit: int = DEFAULT_LIMIT, offset: int = 0) -> dict:
    """
    Managers now see the entire immutable ledger, same as a Super Admin --
    including system-level entries and entries generated by other
    operators. (Previously a Manager was scoped to only entries they
    personally generated; that restriction has been lifted so Managers
    have full audit-trail visibility, matching Admin.)

    PAGINATION (Data Quality & Usability requirement #4): this ledger can
    grow without bound over the system's lifetime, so -- unlike the other
    "directory" listings in this app -- it is never safe to hand back
    "everything that matches". `limit`/`offset` are mandatory-in-spirit
    here (they have small, sane defaults) and `total` tells the caller how
    many pages exist so it can render Prev/Next controls correctly.

    HIDDEN ROOT ADMIN: entries whose `operator` is the hardcoded root
    admin's own synthetic email (SUPER_ADMIN_EMAIL) are excluded from this
    UI-facing listing -- "it's a secure door for the developer" means its
    actions shouldn't show up here even though a Super Admin/Admin/Manager
    otherwise now sees the entire ledger. The row is still written to
    `audit_logs` exactly like any other action (nothing is skipped at
    write time) -- it's only ever filtered out of what THIS function and
    the export functions below hand back, so the real, complete history
    still exists at the database level for anyone with direct DB access.
    """
    limit = max(1, min(limit, MAX_LIMIT))
    offset = max(0, offset)

    query = db.query(models.AuditLog).filter(models.AuditLog.operator != SUPER_ADMIN_EMAIL)

    total = query.count()
    logs = query.order_by(desc(models.AuditLog.timestamp)).offset(offset).limit(limit).all()
    return {"items": logs, "total": total, "limit": limit, "offset": offset}


_EXPORT_HEADERS = ["ID", "Timestamp", "Operator", "Action", "Target Type", "Target ID", "Details"]


def _filtered_audit_logs_query(db: Session, user: dict, start_date: Optional[datetime.date], end_date: Optional[datetime.date]):
    """
    Shared WHERE-clause builder for both export_audit_logs_csv() and
    export_audit_logs_pdf() -- same unscoped visibility as get_audit_logs()
    above (Managers now see every entry, same as a Super Admin), optionally
    narrowed further by an inclusive start/end date range. Returns the
    still-unexecuted query, ordered newest-first, so each caller decides for
    itself whether to stream it (CSV) or materialize it in one shot (PDF).
    """
    query = db.query(models.AuditLog).filter(models.AuditLog.operator != SUPER_ADMIN_EMAIL)
    # `start_date`/`end_date` are plain calendar dates picked from a date
    # input -- a person choosing "2026-07-10" means "that day, in the time
    # I'm looking at" (i.e. DISPLAY_TIMEZONE), not "that day in UTC". Since
    # AuditLog.timestamp is stored/compared as UTC, each boundary is built
    # in DISPLAY_TIMEZONE first and then converted to UTC for the query --
    # otherwise a Lagos (UTC+1) person filtering for "today" would silently
    # lose the last hour of it (and pick up the first hour of the day
    # before) the way a raw UTC-midnight boundary used to.
    if start_date:
        start_dt = datetime.datetime.combine(start_date, datetime.time.min, tzinfo=export_service.DISPLAY_TZ)
        query = query.filter(models.AuditLog.timestamp >= start_dt.astimezone(datetime.timezone.utc))
    if end_date:
        end_dt = datetime.datetime.combine(end_date, datetime.time.max, tzinfo=export_service.DISPLAY_TZ)
        query = query.filter(models.AuditLog.timestamp <= end_dt.astimezone(datetime.timezone.utc))
    return query.order_by(desc(models.AuditLog.timestamp))


def export_audit_logs_csv(db: Session, user: dict, start_date: Optional[datetime.date], end_date: Optional[datetime.date]):
    """
    Returns a generator of CSV rows for the same filtered set of logs as
    get_audit_logs, optionally narrowed further by a start/end date range.

    Generation now happens inside `tasks.export_tasks.generate_audit_export`
    on the Celery `worker` container (see api/audit.py's module docstring
    for why), which drains this generator into one in-memory buffer rather
    than streaming it straight into an HTTP response the way the old
    synchronous `GET /audit-logs/export` router handler used to via
    StreamingResponse -- there's no HTTP response for a background job to
    stream into. It stays a generator (rather than building one big string
    up front) anyway, since that's still the cheaper way to assemble it row
    by row regardless of what ultimately consumes it.

    NOTE: this deliberately does NOT apply limit/offset -- a "give me
    everything in this date range as a file" export is a fundamentally
    different operation from "show me a page of rows in the UI".
    """
    logs = _filtered_audit_logs_query(db, user, start_date, end_date).all()

    def generate_csv():
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(_EXPORT_HEADERS)
        yield output.getvalue()
        output.seek(0)
        output.truncate(0)

        for log in logs:
            # `id`/`target_id` are always plain integers (never
            # attacker/user-controlled text), so they're written as-is.
            # Every free-text column goes through `_csv_safe_cell()` first.
            writer.writerow([
                log.id, export_service.format_export_datetime(log.timestamp),
                _csv_safe_cell(log.operator), _csv_safe_cell(log.action),
                _csv_safe_cell(log.target_type), log.target_id, _csv_safe_cell(log.details),
            ])
            yield output.getvalue()
            output.seek(0)
            output.truncate(0)

    return generate_csv()


def export_audit_logs_pdf(db: Session, user: dict, start_date: Optional[datetime.date], end_date: Optional[datetime.date]) -> bytes:
    """
    PDF equivalent of export_audit_logs_csv(), for a Super Admin/Manager who
    wants a printable copy of the ledger instead of a spreadsheet. Unlike
    the CSV export, this one is built as a single in-memory PDF (reportlab's
    Platypus engine doesn't support incremental/streamed page building), so
    it's intended for the same "narrow it to a date range first" workflow
    the frontend already prompts for -- not for dumping the entire
    unbounded ledger at once.
    """
    logs = _filtered_audit_logs_query(db, user, start_date, end_date).all()
    rows = [
        [log.id, export_service.format_export_datetime(log.timestamp), log.operator, log.action, log.target_type, log.target_id, log.details]
        for log in logs
    ]

    subtitle_bits = [f"Exported by {user['email']}"]
    if start_date:
        subtitle_bits.append(f"from {start_date.isoformat()}")
    if end_date:
        subtitle_bits.append(f"to {end_date.isoformat()}")
    subtitle_bits.append(f"{len(rows)} entr{'y' if len(rows) == 1 else 'ies'}")

    return export_service.build_pdf_bytes(
        "System Immutability Audit Trail", " · ".join(subtitle_bits), _EXPORT_HEADERS, rows,
    )
