import { API_URL } from './api.js';
import { getSession } from './auth.js';
let timer = null;
export async function getMaintenanceStatus(){ const r=await fetch(`${API_URL}/config/public`,{credentials:'include'}); if(!r.ok) throw new Error('Unable to check maintenance status'); return r.json(); }
export function isMaintenanceError(response, body){ return response?.status===503 && body?.code==='MAINTENANCE_MODE'; }
function overlay(config){ let el=document.getElementById('maintenanceOverlay'); if(!el){el=document.createElement('div');el.id='maintenanceOverlay';el.className='fixed inset-0 z-[9999] flex items-center justify-center bg-background p-6';document.body.appendChild(el)}; el.innerHTML=`<section class="w-full max-w-xl rounded-2xl border border-border bg-card p-8 text-center shadow-2xl"><div class="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-amber-500/30 bg-amber-500/10 text-amber-400 text-3xl">⚙</div><div class="mb-3 inline-flex items-center gap-2 rounded-full border border-amber-500/25 bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-300">Maintenance in progress</div><h1 class="text-3xl font-semibold">We’re improving things</h1><p class="mx-auto mt-4 max-w-md text-sm leading-6 text-muted-foreground">${escapeHtml(config.maintenance_message||'We are currently performing scheduled maintenance. Please check back shortly.')}</p><p class="mt-4 text-xs text-muted-foreground">Your data remains safe and unchanged.</p><button id="maintenanceRefresh" class="mt-7 rounded-lg border border-border px-4 py-2 text-sm font-medium hover:bg-muted">Refresh status</button><div class="mt-8 border-t border-border pt-5 text-xs text-muted-foreground"><a href="/" class="hover:text-foreground">Administrator sign in</a></div></section>`;document.getElementById('maintenanceRefresh')?.addEventListener('click',()=>location.reload());}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
export async function initMaintenanceMode(){ if(new URLSearchParams(location.search).has('maintenance_admin')) return false; try{const c=await getMaintenanceStatus();const s=getSession();if(c.maintenance_mode && s?.role!=='super_admin'){overlay(c); if(!timer) timer=setInterval(()=>location.reload(),60000); return true;} if(c.maintenance_mode && s?.role==='super_admin'){const b=document.createElement('div');b.id='maintenanceAdminBanner';b.className='fixed top-0 left-0 right-0 z-[9998] border-b border-amber-300 bg-amber-50 px-4 py-2 text-center text-xs text-amber-950 dark:border-amber-700/60 dark:bg-amber-950/40 dark:text-amber-100';b.innerHTML='<strong>Maintenance mode is active.</strong> Other users cannot access the application.';document.body.prepend(b);} return false;}catch(e){console.warn('Maintenance status unavailable; continuing normally.',e);return false;} }

export async function initMaintenanceControls(){ const toggle=document.getElementById('maintenanceModeToggle'); const msg=document.getElementById('maintenanceModeMessage'); if(!toggle||!msg) return; const session=getSession(); if(session?.role!=="super_admin"){document.getElementById('maintenanceModeSection')?.classList.add('hidden');return;} const live=document.getElementById('maintenanceModeLive'); let enabled=false; const paint=()=>{toggle.textContent=enabled?'Disable Maintenance':'Enable Maintenance';live?.classList.toggle('hidden',!enabled)}; try{const s=await fetch(`${API_URL}/maintenance/status`,{credentials:'include'}).then(r=>r.json());enabled=!!s.enabled;msg.value=s.message||msg.value;paint()}catch(e){console.warn(e)} toggle.addEventListener('click',async()=>{const next=!enabled;if(!confirm(next?'Enable maintenance mode? Other users will immediately be blocked.':'Disable maintenance mode and restore access?'))return;toggle.disabled=true;try{const r=await fetch(`${API_URL}/maintenance/status`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:next,message:msg.value})});if(!r.ok)throw new Error('Unable to update maintenance mode');const s=await r.json();enabled=!!s.enabled;msg.value=s.message;paint()}catch(e){alert(e.message||'Unable to update maintenance mode')}finally{toggle.disabled=false}});}

window.addEventListener('asset-app:maintenance', async ()=>{ try{const c=await getMaintenanceStatus(); if(c.maintenance_mode && getSession()?.role!=='super_admin') overlay(c);}catch{} });
